import {
  Aside,
  Autocomplete,
  Badge,
  Button,
  ButtonGroup,
  Card,
  Col,
  ColorPicker,
  Container,
  Divider,
  Form,
  FormItem,
  Image,
  Input,
  Main,
  Menu,
  MenuItem,
  Option,
  OptionGroup,
  Radio,
  RadioGroup,
  Row,
  Scrollbar,
  Select,
  Slider,
  Submenu,
  Switch,
  TabPane,
  Table,
  TableColumn,
  Tabs,
  Tooltip,
} from 'element-ui'
import Vue from 'vue';

((app: { use(a: any): void }) => {
// 初始化element
  app.use(Aside)
  app.use(Autocomplete)
  app.use(Badge)
  app.use(Button)
  app.use(ButtonGroup)
  app.use(Card)
  app.use(Col)
  app.use(ColorPicker)
  app.use(Container)
  app.use(Divider)
  app.use(Form)
  app.use(FormItem)
  app.use(Image)
  app.use(Input)
  app.use(Main)
  app.use(Menu)
  app.use(MenuItem)
  app.use(Option)
  app.use(OptionGroup)
  app.use(Radio)
  app.use(RadioGroup)
  app.use(Row)
  app.use(Select)
  app.use(Scrollbar)
  app.use(Slider)
  app.use(Submenu)
  app.use(Switch)
  app.use(Table)
  app.use(TableColumn)
  app.use(TabPane)
  app.use(Tabs)
  app.use(Tooltip)
})(Vue)
